# Generated by Django 4.1.3 on 2023-11-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culmicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[('1', 'Administrador'), ('2', 'Profesor'), ('3', 'Estudiante')], default='1', max_length=30, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Usuario'),
        ),
    ]
