# Generated by Django 4.1.3 on 2023-11-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culmicacion', '0002_alter_usuario_password_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[('1', 'Administrador'), ('2', 'Profesor'), ('3', 'Estudiante')], default='1', verbose_name='Rol'),
        ),
    ]
