# Generated by Django 4.1.3 on 2023-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culmicacion', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Profesor'), ('3', 'Estudiante')], default='1', max_length=1, verbose_name='Rol'),
        ),
    ]
